import Link from "next/link";
import { ArrowRight, BookOpenCheck, Building2, ChartNoAxesCombined, CheckCircle2, GraduationCap, Layers3, Network, Sparkles } from "lucide-react";
import { Logo } from "@/components/Logo";
import { ThemeSwitcher } from "@/components/ThemeSwitcher";

const features = [
  { icon: BookOpenCheck, title: "Learning that leads somewhere", text: "Discover practical courses, mentors, and resources built around your next move." },
  { icon: Network, title: "A connected student network", text: "Bring opportunities, university support, and a growing community into one place." },
  { icon: Building2, title: "A clearer path to opportunity", text: "Meet employers, showcase your strengths, and take action with confidence." }
];

export default function HomePage() {
  return <main className="landing-stage min-h-screen text-white">
    <nav className="landing-nav mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-8">
      <Link href="/" className="flex items-center gap-3 focus-ring-dark rounded-xl"><Logo size={43} /><span><strong className="block font-display text-xl leading-none">Excel Smartic</strong><small className="mt-1 block text-[9px] font-bold tracking-[.18em] text-white/45">CONNECT · LEARN · ADVANCE</small></span></Link>
      <div className="hidden items-center gap-7 text-sm font-semibold text-slate-300 md:flex"><a href="#platform" className="hover:text-white">Platform</a><a href="#how-it-works" className="hover:text-white">How it works</a><a href="#impact" className="hover:text-white">Impact</a></div>
      <div className="flex items-center gap-2"><ThemeSwitcher /><Link href="/login" className="landing-signin hidden sm:inline-flex">Sign in</Link><Link href="/signup" className="landing-nav-cta">Get started <ArrowRight size={15} /></Link></div>
    </nav>

    <section className="landing-hero mx-auto grid max-w-7xl gap-12 px-5 pb-20 pt-16 lg:grid-cols-[1fr_.92fr] lg:px-8 lg:pb-28 lg:pt-24">
      <div className="relative z-10 max-w-3xl"><p className="landing-eyebrow"><Sparkles size={15} /> THE STUDENT OPPORTUNITY NETWORK</p><h1 className="landing-title mt-6">One connected hub for the work that moves you forward.</h1><p className="landing-subtitle mt-7">Excel Connect Hub brings learning resources, university services, student community, and real academic opportunities together—so progress feels possible every day.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/signup" className="landing-primary">Start your journey <ArrowRight size={18} /></Link><Link href="/login" className="landing-secondary">Explore your dashboard</Link></div><div className="mt-11 flex flex-wrap gap-x-7 gap-y-3 text-sm text-slate-300">{["Designed for students", "Built for universities", "Made for opportunity"].map((item) => <span key={item} className="flex items-center gap-2"><CheckCircle2 size={17} className="landing-accent" />{item}</span>)}</div></div>
      <div className="hero-visual relative mx-auto w-full max-w-xl" aria-label="Excel Smartic platform overview"><div className="hero-glow" /><div className="hero-console"><div className="hero-console-top"><span className="flex items-center gap-2 text-sm font-bold"><Logo size={27} /> Your progress space</span><span className="rounded-full border border-white/10 px-2.5 py-1 text-[10px] font-bold text-white/55">LIVE</span></div><div className="mt-7 grid grid-cols-[1.15fr_.85fr] gap-3"><div className="hero-metric"><span>Learning path</span><strong>68%</strong><div className="hero-progress"><i /></div><small>3 activities this week</small></div><div className="hero-spotlight"><GraduationCap size={27} /><span>Student profile</span><strong>Ready to grow</strong></div></div><div className="mt-3 grid grid-cols-2 gap-3"><div className="hero-mini"><Layers3 size={18} /><span>Resources</span><strong>24 new</strong></div><div className="hero-mini"><ChartNoAxesCombined size={18} /><span>Opportunities</span><strong>8 matched</strong></div></div></div><div className="hero-float hero-float-one"><BookOpenCheck size={19} /><span><b>Skill checkpoint</b><small>Academic writing complete</small></span><CheckCircle2 size={17} /></div><div className="hero-float hero-float-two"><span className="hero-avatar">AM</span><span><b>Community connection</b><small>Mentor session confirmed</small></span></div></div>
    </section>

    <section id="platform" className="landing-section"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><p className="landing-eyebrow">BUILT AROUND YOUR MOMENTUM</p><div className="mt-5 flex flex-col justify-between gap-5 md:flex-row md:items-end"><h2 className="landing-section-title max-w-xl">Everything you need to keep moving.</h2><p className="max-w-md leading-7 text-slate-400">No scattered tools or missed messages. Just a clearer, more connected experience around your student life.</p></div><div className="mt-11 grid gap-4 md:grid-cols-3">{features.map(({ icon: Icon, title, text }) => <article key={title} className="landing-feature"><Icon className="landing-accent" size={25} /><h3>{title}</h3><p>{text}</p><span>Discover more <ArrowRight size={15} /></span></article>)}</div></div></section>

    <section id="impact" className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="impact-panel"><div><p className="landing-eyebrow">PROGRESS YOU CAN FEEL</p><h2 className="landing-section-title mt-5">Built to turn intention into action.</h2></div><div className="grid grid-cols-2 gap-7 sm:grid-cols-4">{[["01", "Connected profile"], ["02", "Learning plan"], ["03", "Real opportunities"], ["04", "Lasting progress"]].map(([number, text]) => <div key={number}><strong className="impact-number">{number}</strong><p className="mt-2 text-sm text-slate-300">{text}</p></div>)}</div></div></section>

    <section id="how-it-works" className="landing-section"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><p className="landing-eyebrow">HOW IT WORKS</p><div className="mt-9 grid gap-7 lg:grid-cols-[.9fr_1.1fr]"><h2 className="landing-section-title">A simpler rhythm for your goals.</h2><div className="space-y-5">{[["01", "Create your connected profile", "Tell us where you are and where you want to go."], ["02", "Find resources and support", "Access tools, mentors, and services designed for students."], ["03", "Act on the right opportunity", "Turn your preparation into meaningful next steps."]].map(([number, title, text]) => <div key={number} className="how-row"><span>{number}</span><div><h3>{title}</h3><p>{text}</p></div></div>)}</div></div></div></section>
    <section className="mx-auto max-w-7xl px-5 pb-20 lg:px-8"><div className="final-cta"><p className="landing-eyebrow">YOUR NEXT STEP IS HERE</p><h2>Make your student journey more connected.</h2><p>Join Excel Smartic and bring your learning, opportunities, and support network into focus.</p><Link href="/signup" className="landing-primary">Create your account <ArrowRight size={18} /></Link></div></section>
    <footer className="border-t border-white/[.07]"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-5 py-7 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between lg:px-8"><span>© 2026 Excel Smartic. Built for connected progress.</span><div className="flex gap-5"><a href="#platform">Platform</a><Link href="/login">Sign in</Link><Link href="/signup">Create account</Link></div></div></footer>
  </main>;
}
